apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ofk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-betaling-frontend
  app.kubernetes.io/instance: fint-betaling-frontend_ofk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: ofk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/url/hostname"
        value: 'betaling.felleskomponent.no/ofk'
    target:
      kind: Application
      name: fint-betaling-frontend
