apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-betaling-frontend
  labels:
    app.kubernetes.io/name: fint-betaling-frontend
    app.kubernetes.io/instance: fint-betaling-frontend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8000
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: fintlabsacr.azurecr.io/fint-betaling-frontend:c07351656d999955015fe3c567fe319f8f5e407a
  url:
    hostname: betaling.felleskomponent.no
    basePath: /
  ingress:
    enabled: true
    middlewares:
      - fint-betaling-auth-forward-sso
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
  restartPolicy: Always
  replicas: 1
#  strategy:
#    type: RollingUpdate
#    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }